#!/usr/bin/env Rscript
# Generate tiny 10x-like Matrix Market inputs for public smoke tests.

args <- commandArgs(trailingOnly = FALSE)
file_arg <- "--file="
script_path <- sub(file_arg, "", args[grepl(file_arg, args)][1])
if (!is.na(script_path) && nzchar(script_path)) {
  project_root <- normalizePath(file.path(dirname(script_path), "..", ".."), mustWork = FALSE)
} else {
  project_root <- normalizePath(getwd(), mustWork = FALSE)
}

samples <- c("control_1", "control_2", "treatment_1", "treatment_2")
genes <- data.frame(
  id = paste0("ENSMUSG", sprintf("%011d", seq_len(12))),
  symbol = c("Epcam", "Krt8", "Krt18", "Ptprc", "Cd3d", "Cd8a", "Lyz2", "Csf1r", "Col1a1", "Pecam1", "Mki67", "Actb"),
  feature_type = "Gene Expression"
)

write_mtx <- function(mat, path) {
  con <- file(path, open = "wt")
  on.exit(close(con), add = TRUE)
  writeLines("%%MatrixMarket matrix coordinate integer general", con)
  writeLines("% generated by examples/toy_lung_2grp/generate_toy_inputs.R", con)
  nz <- which(mat != 0, arr.ind = TRUE)
  writeLines(sprintf("%d %d %d", nrow(mat), ncol(mat), nrow(nz)), con)
  for (i in seq_len(nrow(nz))) {
    writeLines(sprintf("%d %d %d", nz[i, 1], nz[i, 2], mat[nz[i, 1], nz[i, 2]]), con)
  }
}

set.seed(20260618)
base_dir <- file.path(project_root, "data", "demo", "toy_lung_2grp", "cellranger_out")
for (sample in samples) {
  out_dir <- file.path(base_dir, sample, "outs", "filtered_feature_bc_matrix")
  dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

  barcodes <- paste0(sample, "_cell", sprintf("%03d", seq_len(8)), "-1")
  mat <- matrix(rpois(length(genes$symbol) * length(barcodes), lambda = 2), nrow = nrow(genes))
  rownames(mat) <- genes$symbol
  colnames(mat) <- barcodes

  if (grepl("treatment", sample)) {
    mat[genes$symbol %in% c("Epcam", "Krt8", "Mki67"), ] <- mat[genes$symbol %in% c("Epcam", "Krt8", "Mki67"), ] + 2
  }

  write_mtx(mat, file.path(out_dir, "matrix.mtx"))
  write.table(genes, file.path(out_dir, "features.tsv"), sep = "\t", quote = FALSE, row.names = FALSE, col.names = FALSE)
  writeLines(barcodes, file.path(out_dir, "barcodes.tsv"))
}

manifest <- data.frame(
  sample_id = samples,
  group = sub("_[0-9]+$", "", samples),
  matrix_dir = file.path("data", "demo", "toy_lung_2grp", "cellranger_out", samples, "outs", "filtered_feature_bc_matrix")
)
dir.create(file.path(project_root, "data", "demo", "toy_lung_2grp"), recursive = TRUE, showWarnings = FALSE)
write.csv(manifest, file.path(project_root, "data", "demo", "toy_lung_2grp", "sample_manifest.csv"), row.names = FALSE)

cat("Generated toy inputs for", length(samples), "samples under", base_dir, "\n")
